### ISSUE TITLE
please increase versionCode with each release!

### ISSUE THREAD

**Issue by IzzySoft** [full-disclosure/android-luks#2]
Houston, we've got a little problem there. The updater at IzzyOnDroid just complained:

```
! Binary files /web/ftp/repo/fdroid/repo/eu.fulldisclosure.android.luks_1.apk and /web/ftp/repo/fdroid/repo/eu.fulldisclosure.android.luks_1.1.apk differ
! repo/eu.fulldisclosure.android.luks_1.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

The former means: today's update won't reach anyone already having installed the app, as Android would say "I already have that version". Culprit is [this line](https://github.com/full-disclosure/android-luks/blob/main/android_luks/app/build.gradle#L16) in your `build.gradle`, which still says `versionCode 1`. Android uses that to tell versions apart, so you must always increment that when making a new release.

As for `DEPENDENCY_INFO_BLOCK`, that can easily be avoided by another little change in the very same `build.gradle` file:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

Thanks in advance!

**Comment by full-disclosure** [comment]
Changes have been pushed and apk re-uploaded.
Does it look good now?

**Comment by IzzySoft** [comment]
Yes, thanks, looks fine now:

```
$ iod repo get eu.fulldisclosure.android.luks
eu.fulldisclosure.android.luks: looking for 'https://api.github.com/repos/full-disclosure/android-luks/releases'
eu.fulldisclosure.android.luks: checking tag 'v.1.1'
eu.fulldisclosure.android.luks: lastRelNo set to '1.1', checking for files
eu.fulldisclosure.android.luks: Upstream file date (2024-06-09 21:24) is newer than ours (2024-06-09 17:32).
eu.fulldisclosure.android.luks: returning ['1.1','https://github.com/full-disclosure/android-luks/releases/download/v.1.1/android_luks_v1.1.apk',1717961074]
eu.fulldisclosure.android.luks: 1.0/1.1, https://github.com/full-disclosure/android-luks/releases: https://github.com/full-disclosure/android-luks/releases/download/v.1.1/android_luks_v1.1.apk
- Grabbing update for eu.fulldisclosure.android.luks: OK
- Checking 'repo/eu.fulldisclosure.android.luks_2.apk' for libraries and malware …
- Checking the app's AndroidManifest.xml …
eu.fulldisclosure.android.luks: check if repo contains FUNDING.yml
eu.fulldisclosure.android.luks: looking for 'https://api.github.com/repos/full-disclosure/android-luks/contents/.github'
eu.fulldisclosure.android.luks: looking for 'https://api.github.com/repos/full-disclosure/android-luks/contents/'
eu.fulldisclosure.android.luks: looking for 'https://api.github.com/repos/full-disclosure/.github/contents/'
eu.fulldisclosure.android.luks: Github reports "Not Found" for https://api.github.com/repos/full-disclosure/.github/contents/
eu.fulldisclosure.android.luks: no FUNDING.yml detected.
eu.fulldisclosure.android.luks: no Fastlane configured, skipping Fastlane check.
```

If you want to, I can provide you a starter package for fastlane via PR, with what's set up with [your app here](https://apt.izzysoft.de/packages/eu.fulldisclosure.android.luks) currently. You'd then have the advantage of control over how your app is presented there, as you could edit descriptions and add graphics as you see fit and your changes would be pulled with the next release each time. No binaries needed, just the metadata; be welcome to the [IzzyOnDroid Fastlane Documentation](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) for details. Just let me know, and I'll have it ready in a wink. As for [FUNDING.yml](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository), you can add that if you want – of course makes no sense if you don't ask for funding :wink:

**Comment by full-disclosure** [comment]
Thank you!

**Comment by IzzySoft** [comment]
Gladly! And PS, almost forgot: Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) if you want to link to your app at the IzzyOnDroid repo, e.g. from your Readme :wink:
